services:
  floorplan-3d:
    image: ghcr.io/nj106/floorplan-3d:latest
    container_name: floorplan-3d
    labels:
      - com.centurylinklabs.watchtower.enable=true
    network_mode: bridge
    ports:
      - "8093:80"
    restart: unless-stopped
